name: advisors
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # UI
  flutter_neumorphic: ^3.2.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1

  # SERVICE
  flutter_hooks: ^0.18.1
  responsive_framework: ^0.1.5

  # ARCHITECTURE
  provider: ^6.0.1
  path_provider: ^2.0.7

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - picture/